#!/bin/bash

function feh_pipe()
{
for f in ${1}/*
do
	echo "<item label=\"$(basename ${f%.*})\">
	<action name=\"Execute\">
	<command>feh --bg-scale \"$f\"</command>
	</action>
	</item>"
done
}

echo "<openbox_pipe_menu>"
# Simply change path to suit
#feh_pipe ${HOME}/Backgrounds # add what folders you have backgrounds in
feh_pipe /home/kaze/Pictures/new/
echo "</openbox_pipe_menu>"

